Repository ember-learn/ember-styleguide, pull requests merged in 2023-10, with the labels that each got.

#488 drop support for EOL node < 18
  .github/workflows/ci.yml
  package.json
Labels: breaking

#489 move to release-it for deploys
  RELEASE.md
  changelog.template
  package-lock.json
  package.json
Labels: internal

#491 Drop support for Ember < 3.28
  .github/workflows/ci.yml
  config/ember-try.js
Labels: breaking

#493 Move header anchor styling into styleguide
  addon/styles/addon.css
  addon/styles/header-anchor.css
  docs/concepts/header-anchor.md
Labels: enhancement

#483 Update bottled ember
  package-lock.json
  package.json
Labels: dependencies
